"""The generator — the cheapest enforcement layer the platform has.

ADR-004's rule is "enforce at the earliest layer that makes a rule impossible to get
wrong", and generation is the earliest layer there is: a CI pipeline that is generated
correctly cannot be a CI pipeline someone got wrong.

Templates live in the SDK, next to the library they scaffold, so the two versions can
never skew. And they are GENERATED, not cloned from a template repo: an app created
eighteen months ago carries an eighteen-month-old scaffold with nothing to tell anyone,
which is exactly the failure ADR-001 is about. `insights upgrade-scaffold` re-renders
exactly the files listed in PLATFORM_OWNED and touches nothing else.
"""

from __future__ import annotations

import os
from pathlib import Path
from types import SimpleNamespace

#: Where the reusable workflows live. Generated CI points here, so it must be real -
#: an earlier version hard-coded an org that does not exist, and every tenant's very
#: first Actions run failed at workflow resolution before running a single step.
#:
#: `@v1` is a MOVING major tag, which is ADR-001's floor-not-pin argument applied to
#: the CI contract: a tenant gets pipeline improvements without editing anything, and
#: a breaking change to the workflow interface means cutting v2.
PLATFORM_REPO = os.environ.get("INSIGHTS_PLATFORM_REPO", "KRISHNABR/insights-platform")
#: Where the SDK itself is fetched from until there is an internal package index.
PLATFORM_ORG = os.environ.get("INSIGHTS_SDK_GIT", "https://github.com/KRISHNABR")
PLATFORM_REF = os.environ.get("INSIGHTS_PLATFORM_REF", "v1")

# --------------------------------------------------------------------------------
# What a new app gets
# --------------------------------------------------------------------------------

MANIFEST = """\
# {name} — everything the platform needs to know about this app.
#
# You declare WHAT you need. The platform decides HOW: which image, which credential,
# which cron, which IAM role, which corporate group. You own your code, your image and
# your connections; the platform owns the road they travel on.
apiVersion: v1
app: {name}
team: {team}
kind: {kind}

# Three tiers, and there is no fourth. They NEST: an owner satisfies every check a
# contributor does, and a contributor every check a reader does - so nobody has to be
# listed twice. `require_role("reader")` in your code checks against these.
access:
  manage:
    owners:       [{owner}]     # approve prod · change access · answer for it
    contributors: []            # deploy dev and uat · read logs · NOT prod
    readers:      []            # see it in `insights status`, nothing more

runtime:
  size: small                   # small | medium | large -> cpu/memory/replicas

# The systems this app talks to. `secret:` is a NAME - the value lives in the secret
# store, which your team writes and the platform team cannot read. A credential typed
# here would be in git history forever, so the loader refuses one.
#
#   connections:
#     - name: my-warehouse
#       engine: databricks-sql  # databricks-sql | redshift | postgres | rest | sqlite
#       host: ${{MY_WAREHOUSE_HOST}}
#       secret: my-warehouse-token
#
#   rows = connect("my-warehouse").query("SELECT ...")
connections: []
{kind_block}
"""

WEB_BLOCK = """
web:
  route: /{name}
  type: spa                     # api | spa
                                #   spa  your frontend in static/, served from the
                                #        SAME origin as your API - which is what lets
                                #        the browser hold nothing but a session cookie
                                #   api  JSON only, no frontend
"""

JOB_BLOCK = """
job:
  schedule: "0 6 * * MON"       # cron, in the timezone below
  timezone: UTC
  timeout: 30m                  # SIGTERM at 30m, SIGKILL 30s later
  retries: 2
  concurrency: forbid           # skip this run if the last one is still going
  catchup: false                # do not fire a burst of missed runs after an outage
  on_failure: notify-owners

outputs: []                     # e.g. {{name: summary, kind: file, format: csv, retention: 90d}}
"""

PYPROJECT = """\
# Generated by `insights new-app`. Managed with uv.
#
#   uv sync                  install
#   uv run insights doctor   check this app the way CI will
#
# The lockfile IS committed: two apps on the same SDK floor must resolve to the same
# versions, or "works on my machine" becomes the platform team's problem.
[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  # The only platform dependency. A floor, not a pin. Must match runtime.sdk in
  # app.yaml — CI fails if they disagree.
  "insights-sdk>=0.1,<1",
]

[dependency-groups]
dev = ["pytest>=8.0"]

[tool.uv]
package = false

# Where to FETCH the SDK. The version range above is the contract - a floor, not a
# pin (ADR-001); this only says where a satisfying version comes from.
#
# With an internal package index, delete this block and configure the index once for
# everyone. Until then the git tag stands in for it. `v1` MOVES: re-locking picks up
# patches and minors, and a breaking change means cutting v2.
#
# Never a local path - you clone only this repo, so a path would resolve on the
# platform team's machine and nowhere else.
[tool.uv.sources]
insights-sdk = {{ git = "{PLATFORM_ORG}/insights-sdk.git", tag = "{PLATFORM_REF}" }}

[tool.pytest.ini_options]
pythonpath = ["src"]
"""

INDEX_HTML = """<!doctype html>
<meta charset="utf-8">
<title>{name}</title>
<!--
  Your frontend. Plain HTML and one <script> - no build step, no bundler, no npm.

  The only thing worth noticing: there is NO authentication code here and no token
  anywhere. fetch() is same-origin, so the session cookie the platform's front door
  set rides along automatically. A token in JavaScript is a token in the DOM.

  Replace all of this. The platform serves whatever is in static/; it does not build
  it, and it has no opinion about your framework.
-->
<style>
  :root {{ --bg:#ffffff; --panel:#fbf8fa; --line:#e7e1e5; --line-soft:#f0ebee;
           --text:#1f1c20; --dim:#78707a; --accent:#c2417a; --pink-wash:#fdf5f9 }}
  * {{ box-sizing:border-box }}
  body {{ margin:0; background:var(--bg); color:var(--text);
         font:14px/1.6 ui-monospace,SFMono-Regular,Menlo,monospace }}
  header {{ padding:18px 24px; border-bottom:1px solid var(--line); background:var(--pink-wash);
            display:flex; align-items:baseline; gap:14px; flex-wrap:wrap }}
  h1 {{ font-size:15px; margin:0; letter-spacing:.05em }}
  .who {{ color:var(--dim); font-size:12px }}
  main {{ padding:24px; max-width:900px }}
  table {{ border-collapse:collapse; width:100%; font-size:13px }}
  th {{ text-align:left; color:var(--dim); font-weight:400;
        padding:6px 14px 6px 0; border-bottom:1px solid var(--line) }}
  td {{ padding:8px 14px 8px 0; border-bottom:1px solid var(--line-soft) }}
  .note {{ color:var(--dim); font-size:12px; max-width:62ch; margin:0 0 20px }}
  .err {{ color:#f85149 }}
</style>

<header>
  <h1>{upper}</h1>
  <span class="who" id="who">...</span>
</header>

<main>
  <p class="note">
    This page is <code>static/index.html</code> in your repo. It calls your own API
    below. There is no login code in it &mdash; the platform handled that before your
    app was reached.
  </p>
  <div id="out">loading...</div>
</main>

<script>
const out = document.getElementById('out');
const esc = (s) => String(s ?? '').replace(/[<>&]/g, c => ({{'<':'&lt;','>':'&gt;','&':'&amp;'}}[c]));

// Who the platform says you are. No token, no header - just the session cookie.
fetch('api/me').then(r => r.json()).then(me => {{
  document.getElementById('who').textContent =
    me.trusted ? `${{me.subject}} · ${{me.groups.join(', ')}}` : 'not signed in';
}});

// Your own endpoint. Change this to whatever you built.
fetch('api/hello')
  .then(r => r.ok ? r.json() : Promise.reject(r.status))
  .then(data => {{
    const rows = Array.isArray(data) ? data : [data];
    const cols = [...new Set(rows.flatMap(Object.keys))];
    out.innerHTML = `<table><tr>${{cols.map(c => `<th>${{esc(c)}}</th>`).join('')}}</tr>` +
      rows.map(r => `<tr>${{cols.map(c => `<td>${{esc(r[c])}}</td>`).join('')}}</tr>`).join('') +
      `</table>`;
  }})
  .catch(err => {{
    out.innerHTML = `<p class="err">api/hello returned ${{esc(err)}}</p>
      <p class="note">If that is 401, sign in first by adding
      <code>?as=you@corp.example</code> to this URL once.</p>`;
  }});
</script>
"""

WEB_MAIN = '''\
"""{name} — a web app on Insights Hub.

Two files are yours: this one and app.yaml. The frontend in static/ is yours too,
and the platform only serves it.

What is NOT here, and never needs to be: login, session handling, a credential, a
host, logging setup, or a health endpoint.
"""

from insights_sdk import connect, current_user, get_logger, require_role, web_app

app = web_app()          # login, identity, structured logs, metrics and /healthz
log = get_logger()


@app.get("/api/me")
def me() -> dict:
    """Who the platform says you are. The UI in static/ calls this."""
    caller = current_user()
    return {{"subject": caller.subject, "groups": list(caller.groups), "trusted": caller.trusted}}


@app.get("/api/hello")
def hello() -> list[dict]:
    """Replace me. The UI renders whatever this returns as a table."""
    require_role("reader")       # 403 unless they are listed in app.yaml
    caller = current_user()
    log.info("hello", groups=len(caller.groups))
    return [
        {{"app": "{name}", "you": caller.subject, "status": "it works"}},
    ]


# READING YOUR OWN DATA
#
# Declare the connection in app.yaml, then:
#
#     @app.get("/api/rows")
#     def rows() -> dict:
#         require_role("reader")
#         data = connect("my-warehouse").query("SELECT * FROM my_table LIMIT 10")
#         log.info("read", rows=len(data))     # the SHAPE, never the rows
#         return {{"rows": data}}
'''

JOB_MAIN = '''\
"""{name} — a scheduled job on Insights Hub.

You do not run a scheduler. You declared a schedule in app.yaml; the platform runs you.
"""

from insights_sdk import get_logger, run_job

log = get_logger()


def main() -> None:
    log.info("hello", note="replace me")

    # Add a dataset to app.yaml, then read it like this:
    #
    #     rows = query("your.dataset", "SELECT * FROM your.dataset")
    #     output("summary", summarise(rows))   # declare it in outputs[] first
    #     log.info("done", rows=len(rows))     # log the SHAPE, never the rows


if __name__ == "__main__":
    raise SystemExit(run_job(main))
'''

CI = """\
# Generated. Do not edit.
#
# Runs on every push and PR. Validates, tests — and deploys NOTHING. Keeping "is it
# correct?" separate from "should it go live?" is what lets you open a PR without
# thinking about environments.
name: ci
on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  ci:
    uses: {PLATFORM_REPO}/.github/workflows/ci.yml@{PLATFORM_REF}
    with:
      app: {name}
"""

DEPLOY_DEV = """\
# Generated. Do not edit.
#
# dev deploys itself on every merge to main — app.yaml says auto_deploy: true.
# Nobody approves a dev deploy; that is what dev is for.
name: deploy-dev
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: {PLATFORM_REPO}/.github/workflows/deploy.yml@{PLATFORM_REF}
    with:
      app: {name}
      environment: dev
    secrets: inherit
"""

DEPLOY_UAT = """\
# Generated. Do not edit.
#
# Deliberately manual. The approver list is NOT configured here — the platform
# reconciles the GitHub environment's reviewers from access.manage.contributors in
# app.yaml, so who-can-promote and who-owns-the-app cannot drift apart.
name: deploy-uat
on:
  workflow_dispatch:
    inputs:
      ref:
        description: commit or tag to promote (defaults to the last dev deploy)
        required: false

jobs:
  deploy:
    uses: {PLATFORM_REPO}/.github/workflows/deploy.yml@{PLATFORM_REF}
    with:
      app: {name}
      environment: uat
      ref: ${{{{ inputs.ref }}}}
    secrets: inherit
"""

DEPLOY_PROD = """\
# Generated. Do not edit.
#
# prod PROMOTES an artefact that already passed uat — it does not rebuild. If it
# rebuilt, prod would be running code nobody tested. Approvers come from
# access.manage.owners.
name: deploy-prod
on:
  workflow_dispatch:
    inputs:
      ref:
        description: commit or tag to promote (must already be live in uat)
        required: true

jobs:
  deploy:
    uses: {PLATFORM_REPO}/.github/workflows/deploy.yml@{PLATFORM_REF}
    with:
      app: {name}
      environment: prod
      ref: ${{{{ inputs.ref }}}}
    secrets: inherit
"""

README = """\
# {name}

A {kind} app on Insights Hub, owned by **{team}**.

| | |
|---|---|
| What we wrote | `src/main.py` and `app.yaml` |
| What we inherited | auth, data access, logging, metrics, health, deployment, the image |

## Day one

```bash
uv sync
uv run insights doctor      # check the manifest the way CI will
uv run insights datasets    # what data you can ask for
uv run insights build --show  # exactly what your container will be
```

Everything here except `src/`, `static/` and `app.yaml` was generated and is not yours
to maintain. When the platform improves it you get the change by upgrading the SDK —
run `insights upgrade-scaffold` to pick up new versions of the generated files.
"""

GITIGNORE = """\
__pycache__/
*.py[cod]
.venv/
.pytest_cache/
# Rendered by `insights build`. Derived from app.yaml, never source.
.insights/
"""

# --------------------------------------------------------------------------------
# The container image — rendered, never stored in a tenant repo
# --------------------------------------------------------------------------------

#: The trade-off, stated because it is a real fork. Generating a Dockerfile INTO the
#: tenant's repository would make it visible and independently buildable, which is worth
#: something. It would also make it EDITABLE — and the moment a team edits it, "runs as
#: non-root", "built on a supported base" and "SDK matches the manifest" stop being true
#: and become things CI has to check. Checking is weaker than knowing.
#:
#: So it stays platform-owned, and `insights build --show` prints it. Nothing is hidden;
#: nothing can drift.
DOCKERFILE = """\
# YOUR Dockerfile. Generated once by `insights new-app`; yours to edit from here.
#   app: {name}
#
# The platform does not rewrite this file, does not publish a base image, and does not
# patch one for you. It is an ordinary Python image and you own it - which also means
# you can change the Python version on the next line whenever you need to.
#
# TWO THINGS CI CHECKS, and only two:
#
#   1. the base is PINNED, not :latest   an image you cannot name is one you cannot
#                                        roll back to
#   2. the final USER is not root        a container breakout should land on a user
#                                        that owns nothing
#
# Everything else is a suggestion. Add build stages, system packages, a different
# distro - CI will not stop you.
FROM python:3.12-slim

# uv, pinned, from its official image. It resolves dependencies in the image exactly
# as it does on your laptop.
COPY --from=ghcr.io/astral-sh/uv:0.5.11 /uv /usr/local/bin/uv

RUN useradd --create-home --uid 10001 app
WORKDIR /app

# Your dependencies, from YOUR pyproject.toml, installed from the COMMITTED lockfile.
# --frozen means the lock must already be current: the image resolves exactly what your
# laptop resolved, or the build fails.
#
# Copied before your source so a code change does not reinstall the world.
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project
ENV PATH="/app/.venv/bin:$PATH" PYTHONUNBUFFERED=1 PYTHONDONTWRITEBYTECODE=1
{extra_system}
COPY src/ /app/src/
COPY app.yaml /app/app.yaml
{extra_static}
USER app
{run_block}"""

WEB_RUN_BLOCK = """EXPOSE 8000
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s \\
  CMD python -c "import urllib.request as u,sys; o=u.build_opener(u.ProxyHandler({})); sys.exit(0 if o.open('http://127.0.0.1:8000/healthz').status==200 else 1)"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--app-dir", "src"]
"""

JOB_RUN_BLOCK = """# A job runs to completion and exits. The scheduler starts it; there is no server
# here and nothing to health-check.
CMD ["python", "src/main.py"]
"""


def render_dockerfile(manifest) -> str:
    """Render the Dockerfile a new app starts with.

    Called once, by `insights new-app` and by `insights build --write`. After that the
    file belongs to the repo and nothing regenerates it.

    A team owns their Python version, their distro and their dependency list, exactly
    as in any Python project. The platform publishes no base image, so there is
    nothing here anybody waits for us to patch.
    """
    system = tuple(getattr(manifest, "system_packages", ()) or ())
    extra_system = (
        "\n# runtime.system_packages from app.yaml\n"
        "USER root\n"
        f"RUN apt-get update && apt-get install -y --no-install-recommends {' '.join(system)} \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n"
        if system
        else ""
    )
    is_web = getattr(manifest, "web", None) is not None
    extra_static = "COPY static/ /app/static/\n" if is_web and manifest.web.type == "spa" else ""
    return DOCKERFILE.format(
        name=manifest.app,
        extra_system=extra_system,
        extra_static=extra_static,
        run_block=WEB_RUN_BLOCK if is_web else JOB_RUN_BLOCK,
    )


RUNBOOK = """\
# {name} — runbook

Everything you do to this app after day one. Generated by the platform and kept
current by `insights upgrade-scaffold`, so it does not drift from the tooling.

---

## Make a change

```bash
uv sync                       # once, and after any dependency change
uv run insights doctor        # the same checks CI runs, run locally first
uv run insights run           # a job: run it now, exactly as the scheduler would
uv run insights up            # a web app: the whole local stack, behind the real edge
```

`doctor` and CI run **the same code**. If doctor is green and CI is red, that is a
platform bug — tell us, because the whole point of `doctor` is that it cannot
disagree.

### Test a web change

`insights up` starts the edge, the app and the console. Sign in by appending
`?as=you@corp.example` to the app's URL once; after that a session cookie carries it.

```bash
uv run insights logs --app {name}             # what it did
uv run insights logs --app {name} --startup   # why it did not boot
uv run insights connections --probe           # can it actually reach its systems
```

### Test a job change

```bash
uv run insights run
```

Exit codes are a contract: **0** succeeded · **1** the job broke · **2** the platform
refused it. The scheduler retries 1 and 2 differently, because a refusal will not fix
itself.

---

## Deploy

| Environment | How | Who approves |
|---|---|---|
| dev | every merge to `main` | nobody — it is automatic |
| uat | manual, from Actions | contributors |
| prod | manual, from Actions | owners |

The pipelines are in `.github/workflows/` and the platform owns them: they call a
central reusable workflow, and `insights upgrade-scaffold` updates them. Do not edit
them — your edits will be overwritten, and the version you are running is the version
CI enforces.

**Rolling back** is redeploying the previous image tag from Actions. Your Dockerfile
pins its base, so a rollback gets the image you actually had.

---

## Add a connection

1. Declare it in `app.yaml` under `connections:` — engine, host, and the **name** of a
   secret. Never the value: this file is in git, and a credential here is a credential
   in the history forever. The loader refuses one.
2. Put the value in the secret store at `insights/{name}/<secret-name>`. Your team
   writes it. **The platform team cannot read it** — an explicit IAM Deny, not a
   promise.
3. `uv run insights connections --probe` to check it works.

Locally, write the value to the fake store; `insights connections` prints the exact
path.

---

## When the platform ships a new SDK

> **0.2.0 adds the `mysql` engine and deprecates `Caller.has_role()`.** The old call
> keeps working until 1.0.0 and emits a telemetry record each time, so we can see the
> migration finish rather than assume it did. Use `require_role("reader")`.


Nothing breaks on its own. Your `uv.lock` pins the version you are on, so a release
reaches you when **you** re-lock:

```bash
uv lock --upgrade-package insights-sdk
uv run insights doctor
uv run insights run            # or `insights up`, and click through it
git commit -am "Upgrade insights-sdk"
```

Your `pyproject.toml` declares a **floor and a major bound** (`>=0.1,<1`), not a pin.
Patches and minors are picked up by re-locking; a breaking change means a new major,
which you opt into deliberately.

**The support window is N-2** — the current major plus the two before it. CI fails a
deploy whose SDK is outside it, so you find out at your desk and not on the day you
need to ship something urgent.

If a release deprecates something you use, you get a warning in your telemetry naming
the call, the replacement and the version it goes away in — before it goes away.

```bash
uv run insights upgrade-scaffold --check     # are the generated files current?
uv run insights upgrade-scaffold             # update them, then review the diff
```

---

## When something is wrong

| Symptom | First command |
|---|---|
| It will not start | `insights logs --app {name} --startup` |
| It started, something is off | `insights logs --app {name}` |
| A query is failing | `insights connections --probe` |
| Is it even deployed? | `insights status` |
| What has it been doing? | the console, at `/apps/console/` |

A connection error tells you **who fixes it**: an expired credential is yours, a TLS
or VPC routing failure is ours. If it says ours, tell us and paste the error.

---

## What you must not do

- **Do not edit `.github/workflows/`** — platform-owned, and overwritten on upgrade.
- **Do not put a credential in `app.yaml`** — CI refuses it, and git remembers anyway.
- **Do not run as root in your Dockerfile** — CI refuses it.
- **Do not add a second logger.** `get_logger()` refuses to emit a payload; a
  `logging.getLogger` beside it is an unenforced second path out of the process.

Everything else in this repo is yours, including your Python version.
"""


# --------------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------------

#: Files the PLATFORM owns inside a tenant repository, re-rendered by
#: `insights upgrade-scaffold`. Everything else in a tenant repo is the tenant's.
#: The machine-readable version of "you own your code, we own the road it travels on".
#:
#: The Dockerfile is deliberately NOT here. It is generated once and then belongs to
#: the tenant, so re-rendering it would silently discard their edits. The platform
#: publishes no base image, so there is nothing for it to push into that file anyway.
PLATFORM_OWNED = (
    Path("RUNBOOK.md"),
    Path(".github/workflows/ci.yml"),
    Path(".github/workflows/deploy-dev.yml"),
    Path(".github/workflows/deploy-uat.yml"),
    Path(".github/workflows/deploy-prod.yml"),
)


def render_platform_owned(name: str) -> dict[Path, str]:
    return {
        Path("RUNBOOK.md"): RUNBOOK.format(name=name),
        Path(".github/workflows/ci.yml"): CI.format(name=name, PLATFORM_REPO=PLATFORM_REPO, PLATFORM_REF=PLATFORM_REF),
        Path(".github/workflows/deploy-dev.yml"): DEPLOY_DEV.format(name=name, PLATFORM_REPO=PLATFORM_REPO, PLATFORM_REF=PLATFORM_REF),
        Path(".github/workflows/deploy-uat.yml"): DEPLOY_UAT.format(name=name, PLATFORM_REPO=PLATFORM_REPO, PLATFORM_REF=PLATFORM_REF),
        Path(".github/workflows/deploy-prod.yml"): DEPLOY_PROD.format(name=name, PLATFORM_REPO=PLATFORM_REPO, PLATFORM_REF=PLATFORM_REF),
    }


def generate(*, target: Path, name: str, kind: str, team: str, owner: str) -> list[Path]:
    if target.exists() and any(target.iterdir()):
        raise SystemExit(f"{target} already exists and is not empty")

    kind_block = (WEB_BLOCK if kind == "web" else JOB_BLOCK).format(name=name)

    # render_dockerfile() reads a manifest, and app.yaml does not exist yet - it is
    # being written two lines below. A view with exactly the fields it touches is
    # honest about the coupling and avoids a write-then-reparse dance.
    view = SimpleNamespace(
        app=name,
        kind=kind,
        web=SimpleNamespace(type="spa") if kind == "web" else None,
        system_packages=(),
    )

    files: dict[Path, str] = {
        Path("app.yaml"): MANIFEST.format(
            name=name, team=team, kind=kind, owner=owner, kind_block=kind_block
        ),
        Path("pyproject.toml"): PYPROJECT.format(
            name=name, PLATFORM_ORG=PLATFORM_ORG, PLATFORM_REF=PLATFORM_REF
        ),
        Path("src/main.py"): (JOB_MAIN if kind == "job" else WEB_MAIN).format(name=name),
        **({} if kind == "job" else {
            Path("static/index.html"): INDEX_HTML.format(name=name, upper=name.upper()),
        }),
        Path("README.md"): README.format(name=name, kind=kind, team=team),
        Path(".gitignore"): GITIGNORE,
        # Generated once, then yours. Not in PLATFORM_OWNED, so `upgrade-scaffold`
        # will not overwrite your edits.
        Path("Dockerfile"): render_dockerfile(view),
    }
    files.update(render_platform_owned(name))

    written = []
    for relative, content in files.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written
