"""The generator — the cheapest enforcement layer the platform has.

ADR-004's rule is "enforce at the earliest layer that makes a rule impossible to get
wrong", and generation is the earliest layer there is: a CI pipeline that is generated
correctly cannot be a CI pipeline someone got wrong.

Templates live in the SDK, next to the library they scaffold, so the two versions can
never skew. And they are GENERATED, not cloned from a template repo: an app created
eighteen months ago carries an eighteen-month-old scaffold with nothing to tell anyone,
which is exactly the failure ADR-001 is about. `insights upgrade-scaffold` re-renders
exactly the files listed in PLATFORM_OWNED and touches nothing else.
"""

from __future__ import annotations

from pathlib import Path

# --------------------------------------------------------------------------------
# What a new app gets
# --------------------------------------------------------------------------------

MANIFEST = """\
# {name} — everything the platform needs to know about this app.
#
# You declare WHAT you need. The platform decides HOW: which image, which credential,
# which table, which cron, which IAM role, which corporate group. That is why there is
# no connection string, no Dockerfile and no pipeline in this repository.
apiVersion: v1
app: {name}
team: {team}
kind: {kind}

# Two different questions, deliberately kept apart.
#   manage : who may change, deploy and govern this app   (control plane)
#   roles  : who may use the running app                  (data plane)
# Being able to deploy an app is not the same as being allowed to read what it reads.
access:
  manage:
    owners:       [{owner}]     # approve prod · request data access · answer for it
    contributors: []            # deploy dev and uat · read logs · NOT prod
    readers:      []            # see it in `insights status`, nothing more
  roles: []                     # e.g. {{name: {name}-viewer, groups: [{owner}]}}

runtime:
  sdk: ">=0.1,<1"               # a FLOOR, not a pin. `==` is rejected — see ADR-001
  base: {base}                  # `insights runtimes` lists them. The platform patches these
  size: small                   # small | medium | large

data: []                        # dataset names. `insights datasets` shows what you can ask for
{kind_block}
environments:
  dev:  {{auto_deploy: true}}
  uat:  {{auto_deploy: false, approvers: contributors}}
  prod: {{auto_deploy: false, approvers: owners}}
"""

WEB_BLOCK = """
web:
  route: /{name}
  type: api                     # api | spa | streamlit
                                #   api        JSON only
                                #   spa        your own frontend in static/, served
                                #              from the same origin. We serve it; we
                                #              do not build it
                                #   streamlit  one app.py; we supply the identity
                                #              shim, health sidecar and sticky sessions
"""

JOB_BLOCK = """
job:
  schedule: "0 6 * * MON"       # cron, in the timezone below
  timezone: UTC
  timeout: 30m                  # SIGTERM at 30m, SIGKILL 30s later
  retries: 2
  concurrency: forbid           # skip this run if the last one is still going
  catchup: false                # do not fire a burst of missed runs after an outage
  on_failure: notify-owners

outputs: []                     # e.g. {{name: summary, kind: file, format: csv, retention: 90d}}
"""

PYPROJECT = """\
# Generated by `insights new-app`. Managed with uv.
#
#   uv sync                  install
#   uv run insights doctor   check this app the way CI will
#
# The lockfile IS committed: two apps on the same SDK floor must resolve to the same
# versions, or "works on my machine" becomes the platform team's problem.
[project]
name = "{name}"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  # The only platform dependency. A floor, not a pin. Must match runtime.sdk in
  # app.yaml — CI fails if they disagree.
  "insights-sdk>=0.1,<1",
]

[dependency-groups]
dev = ["pytest>=8.0"]

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["src"]
"""

WEB_MAIN = '''\
"""{name} — a web app on Insights Hub."""

from insights_sdk import current_user, get_logger, query, require_role, web_app

app = web_app()          # login, identity, structured logs, metrics and /healthz
log = get_logger()


@app.get("/api/me")
def me() -> dict:
    caller = current_user()
    return {{"you": caller.subject, "groups": list(caller.groups)}}


# Add a dataset to app.yaml, then read it like this. No connection, no credential,
# no table name — `your.dataset` resolves differently in each environment:
#
#     @app.get("/api/rows")
#     def rows() -> dict:
#         require_role("{name}-viewer")
#         data = query("your.dataset", "SELECT * FROM your.dataset LIMIT 10")
#         log.info("read", rows=len(data))     # log the SHAPE, never the rows
#         return {{"rows": data}}
'''

JOB_MAIN = '''\
"""{name} — a scheduled job on Insights Hub.

You do not run a scheduler. You declared a schedule in app.yaml; the platform runs you.
"""

from insights_sdk import get_logger, run_job

log = get_logger()


def main() -> None:
    log.info("hello", note="replace me")

    # Add a dataset to app.yaml, then read it like this:
    #
    #     rows = query("your.dataset", "SELECT * FROM your.dataset")
    #     output("summary", summarise(rows))   # declare it in outputs[] first
    #     log.info("done", rows=len(rows))     # log the SHAPE, never the rows


if __name__ == "__main__":
    raise SystemExit(run_job(main))
'''

CI = """\
# Generated. Do not edit.
#
# Runs on every push and PR. Validates, tests — and deploys NOTHING. Keeping "is it
# correct?" separate from "should it go live?" is what lets you open a PR without
# thinking about environments.
name: ci
on:
  pull_request:
  push:
    branches-ignore: [main]

jobs:
  ci:
    uses: insights-hub/insights-platform/.github/workflows/ci.yml@v1
    with:
      app: {name}
"""

DEPLOY_DEV = """\
# Generated. Do not edit.
#
# dev deploys itself on every merge to main — app.yaml says auto_deploy: true.
# Nobody approves a dev deploy; that is what dev is for.
name: deploy-dev
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: insights-hub/insights-platform/.github/workflows/deploy.yml@v1
    with:
      app: {name}
      environment: dev
    secrets: inherit
"""

DEPLOY_UAT = """\
# Generated. Do not edit.
#
# Deliberately manual. The approver list is NOT configured here — the platform
# reconciles the GitHub environment's reviewers from access.manage.contributors in
# app.yaml, so who-can-promote and who-owns-the-app cannot drift apart.
name: deploy-uat
on:
  workflow_dispatch:
    inputs:
      ref:
        description: commit or tag to promote (defaults to the last dev deploy)
        required: false

jobs:
  deploy:
    uses: insights-hub/insights-platform/.github/workflows/deploy.yml@v1
    with:
      app: {name}
      environment: uat
      ref: ${{{{ inputs.ref }}}}
    secrets: inherit
"""

DEPLOY_PROD = """\
# Generated. Do not edit.
#
# prod PROMOTES an artefact that already passed uat — it does not rebuild. If it
# rebuilt, prod would be running code nobody tested. Approvers come from
# access.manage.owners.
name: deploy-prod
on:
  workflow_dispatch:
    inputs:
      ref:
        description: commit or tag to promote (must already be live in uat)
        required: true

jobs:
  deploy:
    uses: insights-hub/insights-platform/.github/workflows/deploy.yml@v1
    with:
      app: {name}
      environment: prod
      ref: ${{{{ inputs.ref }}}}
    secrets: inherit
"""

README = """\
# {name}

A {kind} app on Insights Hub, owned by **{team}**.

| | |
|---|---|
| What we wrote | `src/main.py` and `app.yaml` |
| What we inherited | auth, data access, logging, metrics, health, deployment, the image |

## Day one

```bash
uv sync
uv run insights doctor      # check the manifest the way CI will
uv run insights datasets    # what data you can ask for
uv run insights build --show  # exactly what your container will be
```

Everything here except `src/`, `static/` and `app.yaml` was generated and is not yours
to maintain. When the platform improves it you get the change by upgrading the SDK —
run `insights upgrade-scaffold` to pick up new versions of the generated files.
"""

GITIGNORE = """\
__pycache__/
*.py[cod]
.venv/
.pytest_cache/
# Rendered by `insights build`. Derived from app.yaml, never source.
.insights/
"""

# --------------------------------------------------------------------------------
# The container image — rendered, never stored in a tenant repo
# --------------------------------------------------------------------------------

#: The trade-off, stated because it is a real fork. Generating a Dockerfile INTO the
#: tenant's repository would make it visible and independently buildable, which is worth
#: something. It would also make it EDITABLE — and the moment a team edits it, "runs as
#: non-root", "built on a supported base" and "SDK matches the manifest" stop being true
#: and become things CI has to check. Checking is weaker than knowing.
#:
#: So it stays platform-owned, and `insights build --show` prints it. Nothing is hidden;
#: nothing can drift.
DOCKERFILE = """\
# Rendered by `insights build` from app.yaml. NOT stored in the tenant repo.
#   app:  {name}
#   base: {base}
#
# Everything below is a consequence of what was declared. To change it, change
# app.yaml or pyproject.toml - and if neither can express what you need, that is a
# platform gap and we treat it as a bug rather than a request to work around (ADR-004).
FROM insights-hub/{base}:{base_version}

# Your dependencies, from YOUR pyproject.toml, installed from the COMMITTED lockfile.
# --frozen means the lock must already be current: the image resolves exactly what your
# laptop resolved, or the build fails. "Works on my machine" is not debuggable by a
# platform team of three.
#
# Copied before your source so a code change does not reinstall the world.
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project
{extra_system}
COPY src/ /app/src/
COPY app.yaml /app/app.yaml
{extra_static}"""

#: The published family and their pinned versions. `insights runtimes` reads this.
BASE_VERSIONS = {
    "python-web": "0.1",
    "python-data": "0.1",
    "python-min": "0.1",
    "python-streamlit": "0.1",
}


def render_dockerfile(manifest) -> str:
    """Render the image definition for an app, from what it declared.

    Three sources, and the split is the point:

      runtime.base           the platform's runtime and the SDK   (ours)
      pyproject.toml         the app's Python dependencies        (yours)
      runtime.system_packages  apt-level needs, e.g. libgeos      (yours, declared)

    A team never chooses a base OS, a Python version or a user id - but they own their
    own dependency list, exactly as they would in any Python project. That is what
    "bring your code" has to mean, or the platform is a cage.
    """
    system = tuple(getattr(manifest, "system_packages", ()) or ())
    extra_system = (
        "\n# runtime.system_packages from app.yaml - the long tail, without a bespoke image\n"
        "USER root\n"
        f"RUN apt-get update && apt-get install -y --no-install-recommends {' '.join(system)} \\\n"
        "    && rm -rf /var/lib/apt/lists/*\n"
        "USER insights\n"
        if system
        else ""
    )
    extra_static = (
        "COPY static/ /app/static/\n"
        if manifest.web is not None and manifest.web.type == "spa"
        else ""
    )
    return DOCKERFILE.format(
        name=manifest.app,
        base=manifest.base,
        base_version=BASE_VERSIONS.get(manifest.base, "0.1"),
        extra_system=extra_system,
        extra_static=extra_static,
    )


# --------------------------------------------------------------------------------
# Generation
# --------------------------------------------------------------------------------

#: Files the PLATFORM owns inside a tenant repository, re-rendered by
#: `insights upgrade-scaffold`. Everything else in a tenant repo is the tenant's.
#: The machine-readable version of "you own your code, we own the road it travels on".
#: Note the Dockerfile is absent — it is not in the tenant repo at all.
PLATFORM_OWNED = (
    Path(".github/workflows/ci.yml"),
    Path(".github/workflows/deploy-dev.yml"),
    Path(".github/workflows/deploy-uat.yml"),
    Path(".github/workflows/deploy-prod.yml"),
)


def render_platform_owned(name: str) -> dict[Path, str]:
    return {
        Path(".github/workflows/ci.yml"): CI.format(name=name),
        Path(".github/workflows/deploy-dev.yml"): DEPLOY_DEV.format(name=name),
        Path(".github/workflows/deploy-uat.yml"): DEPLOY_UAT.format(name=name),
        Path(".github/workflows/deploy-prod.yml"): DEPLOY_PROD.format(name=name),
    }


def generate(*, target: Path, name: str, kind: str, team: str, owner: str) -> list[Path]:
    if target.exists() and any(target.iterdir()):
        raise SystemExit(f"{target} already exists and is not empty")

    base = "python-web" if kind == "web" else "python-data"
    kind_block = (WEB_BLOCK if kind == "web" else JOB_BLOCK).format(name=name)

    files: dict[Path, str] = {
        Path("app.yaml"): MANIFEST.format(
            name=name, team=team, kind=kind, owner=owner, base=base, kind_block=kind_block
        ),
        Path("pyproject.toml"): PYPROJECT.format(name=name),
        Path("src/main.py"): (JOB_MAIN if kind == "job" else WEB_MAIN).format(name=name),
        Path("README.md"): README.format(name=name, kind=kind, team=team),
        Path(".gitignore"): GITIGNORE,
    }
    files.update(render_platform_owned(name))

    written = []
    for relative, content in files.items():
        path = target / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        written.append(path)
    return written
